# Ejemplo de configuración de secretos para Streamlit Cloud
# Copia este archivo como .streamlit/secrets.toml y completa con tus valores

[google_analytics]
# Property IDs de Google Analytics 4
clarin_property_id = "287171418"
ole_property_id = "151714594"
okdiario_property_id = "255037852"

# Google Sheets
spreadsheet_id = "1bT6C0VI_U7IEmI-ULPHJEvaOkL1mgCozWJIxdNavKBc"

# Credenciales OAuth2 para Google Analytics (desde el archivo JSON)
[google_oauth]
type = "authorized_user"
client_id = "tu_client_id_aqui"
client_secret = "tu_client_secret_aqui" 
refresh_token = "tu_refresh_token_aqui"

# Si usas cuenta de servicio, usa esta sección en su lugar:
# [google_service_account]
# type = "service_account"
# project_id = "tu_project_id"
# private_key_id = "tu_private_key_id"
# private_key = "-----BEGIN PRIVATE KEY-----\ntu_private_key_aqui\n-----END PRIVATE KEY-----\n"
# client_email = "tu_service_account_email@tu_project.iam.gserviceaccount.com"
# client_id = "tu_client_id"
# auth_uri = "https://accounts.google.com/o/oauth2/auth"
# token_uri = "https://oauth2.googleapis.com/token"