# Ejemplo de configuración de secretos para Streamlit Cloud
# Copia este archivo como .streamlit/secrets.toml y completa con tus valores

[google_analytics]
# Property IDs de Google Analytics 4
clarin_property_id = "287171418"
ole_property_id = "151714594"
okdiario_property_id = "255037852"

# Google Sheets
spreadsheet_id = "1bT6C0VI_U7IEmI-ULPHJEvaOkL1mgCozWJIxdNavKBc"

# Credenciales OAuth2 - CUENTA 1 (para Clarín)
[google_oauth_acceso]
type = "authorized_user"
client_id = "tu_client_id_cuenta1"
client_secret = "tu_client_secret_cuenta1" 
refresh_token = "tu_refresh_token_cuenta1"

# Credenciales OAuth2 - CUENTA 2 (para medios)  
[google_oauth_medios]
type = "authorized_user"
client_id = "tu_client_id_cuenta2"
client_secret = "tu_client_secret_cuenta2"
refresh_token = "tu_refresh_token_cuenta2"